# Generated by Django 4.0.6 on 2022-07-18 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Дата начала')),
                ('time_end', models.DateTimeField(verbose_name='Дата окончания')),
                ('repeat', models.BooleanField(default=False, verbose_name='Повторяется ли событие?')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за услугу')),
                ('telegrambool', models.BooleanField(default=False, verbose_name='Оповещать по телеграмм?')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(verbose_name='Телеграмм ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('start', models.DateTimeField(verbose_name='Дата начала события')),
                ('end', models.DateTimeField(verbose_name='Дата окончания события')),
                ('paid', models.BooleanField(default=False, verbose_name='Произошла ли оплата?')),
                ('price_event', models.PositiveIntegerField(verbose_name='Цена за урок')),
                ('master_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.calendar', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Репетитор')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Заказчик')),
                ('description', models.TextField(blank=True, default='Поле для заметок', null=True, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Репетитор')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.customer', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.profile', verbose_name='Пользователь'),
        ),
    ]
