# Generated by Django 4.0.6 on 2022-07-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url',
        ),
    ]
