# Generated by Django 4.0.6 on 2022-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priceevent',
            field=models.PositiveIntegerField(default=400, verbose_name='Цена за урок'),
            preserve_default=False,
        ),
    ]
