# Generated by Django 4.0.6 on 2022-07-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_event_priceevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='priceevent',
            new_name='price_event',
        ),
    ]
