# Generated by Django 4.0.6 on 2022-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0005_rename_priceevent_event_price_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, default='Поле для заметок', null=True, verbose_name='Описание'),
        ),
    ]
